import { vi } from 'vitest'

export const client = {
  listCases: vi.fn().mockResolvedValue({ cases: [] }),
  getCase: vi.fn().mockResolvedValue({ case: undefined, body: '' }),
  createCase: vi.fn().mockResolvedValue({ case: undefined, filePath: '' }),
  updateCase: vi.fn().mockResolvedValue({ case: undefined }),
  deleteCase: vi.fn().mockResolvedValue({ filePath: '' }),
  listSuites: vi.fn().mockResolvedValue({ suites: [] }),
  getSuite: vi.fn().mockResolvedValue({ suite: undefined }),
  createSuite: vi.fn().mockResolvedValue({ suite: undefined, filePath: '' }),
  updateSuite: vi.fn().mockResolvedValue({ suite: undefined }),
  deleteSuite: vi.fn().mockResolvedValue({ filePath: '' }),
  listRuns: vi.fn().mockResolvedValue({ runs: [] }),
  getRun: vi.fn().mockResolvedValue({ run: undefined }),
  createRun: vi.fn().mockResolvedValue({ run: undefined, dirPath: '' }),
  recordResult: vi.fn().mockResolvedValue({ result: undefined }),
  bulkRecordResults: vi.fn().mockResolvedValue({ results: [], pendingCount: 0, totalCount: 0 }),
  finalizeRun: vi.fn().mockResolvedValue({ run: undefined }),
  deleteRun: vi.fn().mockResolvedValue({ dirPath: '' }),
  getPendingCases: vi.fn().mockResolvedValue({ cases: [], totalInScope: 0 }),
  getRepoStatus: vi.fn().mockResolvedValue({
    totalCases: 0,
    highPriority: 0,
    mediumPriority: 0,
    lowPriority: 0,
    passedCount: 0,
    failedCount: 0,
    blockedCount: 0,
    skippedCount: 0,
    neverRunCount: 0,
    activeRuns: [],
    totalRuns: 0,
    totalSuites: 0,
    coverageEntries: [],
  }),
  getCoverageReport: vi.fn().mockResolvedValue({ entries: [], runCount: 0 }),
  getAffectedCases: vi.fn().mockResolvedValue({ cases: [], reason: '' }),
  getGitHubInstallUrl: vi.fn().mockResolvedValue({ url: '', configured: false }),
  handleGitHubCallback: vi.fn().mockResolvedValue({ repositories: [] }),
  listRepositories: vi.fn().mockResolvedValue({ repositories: [] }),
  syncRepository: vi.fn().mockResolvedValue({ repository: undefined }),
  removeRepository: vi.fn().mockResolvedValue({}),
}
