# This file is managed by Centy. Use the Centy CLI to modify it.
name: User Story
icon: person
identifier: uuid
features:
  displayNumber: true
  priority: true
  softDelete: true
  assets: true
  orgSync: true
  move: true
  duplicate: true
priorityLevels: 3
template: template.md
listed: true
